# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "rtsx_usb_sdmmc" "bcache" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  services.fstrim.interval = "daily";
  services.btrfs.autoScrub = { enable = true; };
  services.snapper.configs = {
    home = {
      subvolume = "/home";
      extraConfig = ''
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_wangzi = {
      subvolume = "/home/wangzi";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_config = {
      subvolume = "/home/wangzi/.config";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_local = {
      subvolume = "/home/wangzi/.local";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_download = {
      subvolume = "/home/wangzi/下载";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_public = {
      subvolume = "/home/wangzi/公共";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_picture = {
      subvolume = "/home/wangzi/图片";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_video = {
      subvolume = "/home/wangzi/视频";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_music = {
      subvolume = "/home/wangzi/音乐";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_temp = {
      subvolume = "/home/wangzi/Temp";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_vbox = {
      subvolume = "/home/wangzi/VirtualBox VMs";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=0
        TIMELINE_LIMIT_DAILY=3
        TIMELINE_LIMIT_WEEKLY=1
        TIMELINE_LIMIT_MONTHLY=0
        TIMELINE_LIMIT_YEARLY=0
      '';
    };
    home_document = {
      subvolume = "/home/wangzi/文档";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=24
        TIMELINE_LIMIT_DAILY=7
        TIMELINE_LIMIT_WEEKLY=4
        TIMELINE_LIMIT_MONTHLY=1
        TIMELINE_LIMIT_YEARLY=1
      '';
    };
    home_workspace = {
      subvolume = "/home/wangzi/workspace";
      extraConfig = ''
        ALLOW_USERS="wangzi"
        TIMELINE_LIMIT_HOURLY=24
        TIMELINE_LIMIT_DAILY=7
        TIMELINE_LIMIT_WEEKLY=4
        TIMELINE_LIMIT_MONTHLY=1
        TIMELINE_LIMIT_YEARLY=1
      '';
    };
  };

  hardware.bluetooth.enable = true;
}
