require("widget.panel")
require("widget.window_switcher")
require("widget.scratchpad")
require("widget.info_center")
require("widget.control_center")
require("widget.lockscreen")
require("widget.exitscreen")
