{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  services.power-profiles-daemon.enable = false;
  boot.loader = {
    systemd-boot.enable = true;
    systemd-boot.configurationLimit = 5;
    efi = {
      canTouchEfiVariables = true;
    };
    timeout = 1;
  };
  boot.kernelParams = [
    "i915.enable_gvt=1"
    "intel_iommu=on"
    "iommu=pt"
    "i915.enable_guc=1"
    "i915.enable_fbc=1"
    "pcie_aspm=off"
  ];
  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.blacklistedKernelModules = [ "uvcvideo" ];
  boot.kernelModules = [
    "kvm-intel"
    "dm-snapshot"
    "dm-raid"
    "dm-cache-default"
    "dm-thin-pool"
    "dm-mirror"
  ];

  environment.systemPackages = with pkgs; [
    openrgb
    lm_sensors
    liquidctl
  ];

  services.hardware.openrgb = {
    enable = true;
    motherboard = "intel";
  };

  boot.extraModulePackages = with config.boot.kernelPackages; [
    asus-ec-sensors
  ];
  boot.tmp.cleanOnBoot = false;
  boot.tmp.useTmpfs = false;
  services.udev.extraRules = ''
    SUBSYSTEM=="drivers", DEVPATH=="/bus/pci/drivers/mt7921e", ATTR{new_id}="14c3 0608"
  '';
  boot.extraModprobeConfig = ''
    alias pci:v000014C3d00000608sv*sd*bc*sc*i* mt7921e
  '';

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b0e6efba-4627-4326-96db-e649592ce2c9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/21E6-1EB0";
    fsType = "vfat";
  };

  fileSystems."/mnt/weed/server" = {
    device = "/dev/disk/by-uuid/ff337eaf-f0e7-468c-b23f-68a2ee2c0c73";
    fsType = "btrfs";
    options = [
      "rw"
      "noatime"
    ];
  };
  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/ff337eaf-f0e7-468c-b23f-68a2ee2c0c73";
    fsType = "btrfs";
    options = [
      "rw"
      "noatime"
    ];
  };
  services.btrfs.autoScrub = {
    enable = true;
  };

  swapDevices = [ ];

  hardware = {
    cpu.intel.updateMicrocode = true;
    graphics = {
      extraPackages32 = with pkgs.pkgsi686Linux; [ mesa ];
      extraPackages = with pkgs; [
        mesa
        vpl-gpu-rt
      ];
    };
  };

  services.xserver = {
    modules = with pkgs.xorg; [
      xf86videoamdgpu
      xf86inputlibinput
      xf86videodummy
      xf86videovesa
    ];
    videoDrivers = [ "modestting" ];
  };

  environment.etc."sysconfig/lm_sensors".text = ''
    HWMON_MODULES="coretemp"
  '';

  hardware.fancontrol = {
    enable = false;
    config = ''
      # Configuration file generated by pwmconfig, changes will be lost
      INTERVAL=10
      DEVPATH=hwmon1=devices/platform/nct6775.2592 hwmon2=devices/platform/coretemp.0
      DEVNAME=hwmon1=nct6779 hwmon2=coretemp
      FCTEMPS=hwmon1/pwm2=hwmon2/temp1_input
      FCFANS=hwmon1/pwm2=hwmon1/fan2_input
      # The temperature (°C) at which to SHUT OFF the CPU fan. Efficient CPUs often will not need a fan while idling. Be sure to set this to a temperature that you know is safe. Setting this to 0 is not recommended and may ruin your hardware!
      MINTEMP=hwmon1/pwm2=30
      # The temperature (°C) at which to spin the fan at its MAXIMUM speed. This should be probably be set to perhaps 10 or 20 degrees (°C) below your CPU's critical/shutdown temperature. Setting it closer to MINTEMP will result in higher fan speeds overall.
      MAXTEMP=hwmon1/pwm2=60
      # The PWM value at which your fan starts to spin again. This is often a higher value than MINSTOP as more voltage is required to overcome inertia.
      MINSTART=hwmon1/pwm2=120
      # The PWM value at which your fan stops spinning. Each fan is a little different. Power tweakers can echo different values (between 0 and 255) to /sys/class/hwmon/hwmon0/device/pwm1 and then watch the CPU fan. When the CPU fan stops, use this value.
      MINSTOP=hwmon1/pwm2=0
      # The PWM value to use when the temperature is over MAXTEMP.  If this value isn't defined, it defaults to 255 (full speed).
      MAXPWM=hwmon1/pwm2=255
    '';
  };

  # services.xserver.monitorSection = ''Modeline "1920x1080" 23.53 1920 1952 2040 2072 1080 1106 1108 1135'';
  # services.xserver.resolutions = [{ x = "1920"; y = "1080"; }];
  # services.xserver.displayManager.autoLogin = {
  # enable = true;
  # user = "wangzi";
  # };
  # services.xserver.displayManager.defaultSession = lib.mkForce "none+awesome";
}
